In [1]:
import pandas as pd

In [2]:
base = pd.read_excel("C:\\Users\\rapha\\Desktop\\Lara\\TCR\\Bases_TCR\\Bases_V7\\database_v7.xlsx", sheet_name="Sheet1")

In [3]:
base.head()

,Unnamed: 0,Unnamed: 0.1,TP_CASO,SEXO,IDADE,LOCAL_NASC,RACA_COR,ESCOLARIDADE,CLIN_1_ATEND,CLIN_INICIO_TRAT,...,PERIODO_TRAT,PERIODO_OBITO,ANO,STATUS_DESF,PRIMA_TRAT2,ESQUEMA_TERAPEUTICO,HOSPITAL,DIAG-CLINICO,PERIODO,Estado de vida
0,0,0,1,Feminino,50,RJ,Parda,Fundamental completo,15,25,...,8,1,2012,Negativo,Radioterapia/Quimioterapía,Bimodalidade,Outras instituições,2012-07-02,2012 - 4º Bimestre,Vivo
1,1,1,1,Feminino,76,MA,Branca,Fundamental incompleto,15,24,...,4,1,2012,Positivo,Radioterapia/Quimioterapía,Bimodalidade,Outras instituições,2012-09-17,2012 - 5º Bimestre,Vivo
2,2,2,1,Feminino,39,RJ,Branca,Sem informação,15,15,...,11,1,2012,Positivo,Radioterapia/Quimioterapía,Monomodalidade,Outras instituições,2012-07-05,2012 - 4º Bimestre,Vivo
3,3,3,1,Feminino,58,RJ,Preta,Sem informação,15,15,...,2,6,2012,Negativo,Radioterapia/Quimioterapía,Monomodalidade,Instituto Nacional do Câncer II,2011-07-26,2012 - 1º Bimestre,Morto
4,4,4,1,Feminino,44,RN,Parda,Fundamental incompleto,15,15,...,7,1,2012,Positivo,Radioterapia/Quimioterapía,Bimodalidade,Instituto Nacional do Câncer II,2012-04-24,2012 - 3º Bimestre,Vivo

In [4]:
base.loc[ base['TRAT-DIAG'] <= 60, 'LEI60'] = 'Tempo adequado'
base.loc[base['TRAT-DIAG'] > 60, 'LEI60'] = 'Tempo inadequado'

In [5]:
base.head()

,Unnamed: 0,Unnamed: 0.1,TP_CASO,SEXO,IDADE,LOCAL_NASC,RACA_COR,ESCOLARIDADE,CLIN_1_ATEND,CLIN_INICIO_TRAT,...,PERIODO_OBITO,ANO,STATUS_DESF,PRIMA_TRAT2,ESQUEMA_TERAPEUTICO,HOSPITAL,DIAG-CLINICO,PERIODO,Estado de vida,LEI60
0,0,0,1,Feminino,50,RJ,Parda,Fundamental completo,15,25,...,1,2012,Negativo,Radioterapia/Quimioterapía,Bimodalidade,Outras instituições,2012-07-02,2012 - 4º Bimestre,Vivo,Tempo adequado
1,1,1,1,Feminino,76,MA,Branca,Fundamental incompleto,15,24,...,1,2012,Positivo,Radioterapia/Quimioterapía,Bimodalidade,Outras instituições,2012-09-17,2012 - 5º Bimestre,Vivo,Tempo inadequado
2,2,2,1,Feminino,39,RJ,Branca,Sem informação,15,15,...,1,2012,Positivo,Radioterapia/Quimioterapía,Monomodalidade,Outras instituições,2012-07-05,2012 - 4º Bimestre,Vivo,Tempo inadequado
3,3,3,1,Feminino,58,RJ,Preta,Sem informação,15,15,...,6,2012,Negativo,Radioterapia/Quimioterapía,Monomodalidade,Instituto Nacional do Câncer II,2011-07-26,2012 - 1º Bimestre,Morto,Tempo inadequado
4,4,4,1,Feminino,44,RN,Parda,Fundamental incompleto,15,15,...,1,2012,Positivo,Radioterapia/Quimioterapía,Bimodalidade,Instituto Nacional do Câncer II,2012-04-24,2012 - 3º Bimestre,Vivo,Tempo inadequado

In [6]:
base.to_excel('C:\\Users\\rapha\\Desktop\\Lara\\TCR\\Bases_TCR\lei60.xlsx')

In [8]:
base.describe()

,Unnamed: 0,Unnamed: 0.1,TP_CASO,CLIN_1_ATEND,CLIN_INICIO_TRAT,ANO_PRIMA_DIAG,ANO_PRIMA_CONS,ANO_INICIO_TRAT,CONS-DIAG,TRAT-DIAG,TRAT-CONS,OBITO-TRAT,OBITO-DIAG,OBITO-CONS,PERIODO_DIAG,PERIODO_TRAT,PERIODO_OBITO,ANO
count,4120.000000,4120.000000,4120.0,4120.000000,4120.000000,4120.000000,4120.000000,4010.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000,4120.000000
mean,2059.500000,2059.500000,1.0,15.628641,17.681311,2018.046359,2014.360437,2014.554364,124.007039,-2869.456311,-2993.463350,55964.433010,53094.976699,52970.969660,6.458252,6.382524,2.246845,2014.360437
std,1189.485883,1189.485883,0.0,4.475875,10.846415,175.916323,1.681465,1.749365,2573.683130,18745.156494,18562.224513,33665.935094,28031.597947,27881.766851,3.401399,3.416295,2.865944,1.681465
min,0.000000,0.000000,1.0,0.000000,1.000000,1978.000000,2012.000000,2012.000000,0.000000,-116133.000000,-116133.000000,0.000000,-114238.000000,-114365.000000,1.000000,1.000000,1.000000,2012.000000
25%,1029.750000,1029.750000,1.0,15.000000,15.000000,2013.000000,2013.000000,2013.000000,12.750000,70.000000,38.000000,66543.750000,66652.000000,66610.500000,4.000000,3.000000,1.000000,2013.000000
50%,2059.500000,2059.500000,1.0,15.000000,15.000000,2014.000000,2014.000000,2014.000000,29.000000,105.000000,65.000000,67319.500000,67430.000000,67362.500000,6.000000,6.000000,1.000000,2014.000000
75%,3089.250000,3089.250000,1.0,15.000000,15.000000,2016.000000,2016.000000,2016.000000,60.250000,155.000000,99.000000,68032.000000,68110.000000,68046.250000,9.000000,9.000000,1.000000,2016.000000
max,4119.000000,4119.000000,1.0,46.000000,99.000000,9999.000000,2017.000000,2019.000000,115965.000000,115965.000000,827.000000,182621.000000,182621.000000,68665.000000,12.000000,12.000000,12.000000,2017.000000